/* ─────────────────────────────────────────────────────────────
   Mock Data - Client-side Data for Premium UI Display
   ───────────────────────────────────────────────────────────── */

/**
 * Represents a single scalar metric displayed in the analytics dashboard.
 */
export interface MetricData {
  label: string;
  value: string | number;
  unit?: string;
  icon?: string;
  trend?: 'up' | 'down' | 'stable';
  trendPercent?: number;
}

/**
 * Defines a mathematical formulation associated with the simulation engine.
 * Includes LaTeX formatting for rendering and descriptive metadata for the UI.
 */
export interface Formula {
  id: string;
  title: string;
  latex: string;
  category: 'fluid-dynamics' | 'risk-assessment' | 'mitigation' | 'density';
  description: string;
  variables?: Array<{
    symbol: string;
    meaning: string;
  }>;
  explanation: string;
}

/**
 * Captures an instantaneous snapshot of the simulation state, aggregating metrics and active alerts.
 */
export interface AnalyticsSnapshot {
  timestamp: string;
  metrics: MetricData[];
  alerts: AlertItem[];
  riskLevel: 'low' | 'medium' | 'high' | 'critical';
}

/**
 * Represents a localized or systemic hazard notification generated by the simulation engine.
 */
export interface AlertItem {
  id: string;
  level: 'info' | 'warning' | 'critical';
  message: string;
  timestamp: string;
  location?: string;
}

/**
 * Encapsulates the execution metadata of the active simulation instance.
 */
export interface SimulationState {
  status: 'idle' | 'running' | 'paused' | 'completed';
  step: number;
  elapsed: number;
  progress: number;
}

/* ───────────────────────────────────────────────────────────── */
/* FORMULAS DATA - Complex Mathematical Representations */
/* ───────────────────────────────────────────────────────────── */

export const FORMULAS: Formula[] = [
  {
    id: 'harmonic-potential',
    title: 'Harmonic Potential Field',
    latex: '\\nabla^2 \\phi = 0, \\quad \\phi|_{\\partial\\Omega_{exit}} = 0',
    category: 'fluid-dynamics',
    description: 'Guiding direction field via Laplace equation',
    variables: [
      { symbol: '\\phi', meaning: 'Navigation potential' },
      { symbol: '\\nabla^2', meaning: 'Laplace operator' },
    ],
    explanation:
      'Solves for a smooth potential field where the gradient -\\nabla\\phi provides the optimal direction toward exits while respecting geometric constraints.',
  },
  {
    id: 'density-velocity',
    title: 'Density-Dependent Velocity',
    latex: '\\mathbf{v}[\\rho] = -\\nabla \\phi \\left(1 - \\frac{\\rho}{\\rho_{max}}\\right)^\\beta',
    category: 'fluid-dynamics',
    description: 'Velocity degradation under congestion',
    variables: [
      { symbol: '\\rho_{max}', meaning: 'Maximum capacity' },
      { symbol: '\\beta', meaning: 'Mobility exponent' },
    ],
    explanation:
      'Models the reduction in walking speed as local density approaches saturation. As density nears rho_max, mobility vanishes.',
  },
  {
    id: 'density-evolution',
    title: 'Density Evolution Equation',
    latex: '\\partial_t \\rho + \\nabla \\cdot (\\rho \\mathbf{v}) = D\\nabla^2 \\rho - \\nabla \\cdot (\\rho \\nabla P(\\rho))',
    category: 'fluid-dynamics',
    description: 'Nonlinear advection-diffusion-pressure system',
    variables: [
      { symbol: 'D', meaning: 'Diffusion coefficient' },
      { symbol: 'P(\\rho)', meaning: 'Nonlinear pressure' },
    ],
    explanation:
      'The core governing equation capturing directed flow (advection), random spreading (diffusion), and high-density repulsion (pressure).',
  },
  {
    id: 'pressure-law',
    title: 'Smooth Pressure Law',
    latex: 'P(\\rho) = k \\left(\\frac{\\rho}{\\rho_{crit}}\\right)^n \\frac{1}{1 + e^{-a(\\rho - \\rho_{crit})}}',
    category: 'fluid-dynamics',
    description: 'Super-quadratic pressure activation',
    variables: [
      { symbol: '\\rho_{crit}', meaning: 'Critical density' },
      { symbol: 'a', meaning: 'Activation steepness' },
    ],
    explanation:
      'Defines the repulsive force that emerges when density exceeds the critical threshold. Uses a sigmoid activation to ensure differentiability.',
  },
  {
    id: 'risk-functional',
    title: 'Risk Functional Index',
    latex: 'R = \\alpha \\frac{\\rho}{\\rho_{max}} + \\delta \\frac{1}{d + \\epsilon} + \\gamma \\frac{1}{|v| + \\epsilon} + \\eta \\Psi(\\rho) - c',
    category: 'risk-assessment',
    description: 'Multi-factor stampede risk quantification',
    variables: [
      { symbol: '\\Psi', meaning: 'Instability indicator' },
      { symbol: 'c', meaning: 'Camaraderie term' },
      { symbol: '\\epsilon', meaning: 'Regularization' },
    ],
    explanation:
      'Quantifies local danger by combining density, proximity to constraints, stagnancy, and structural instability precursors.',
  },
  {
    id: 'camaraderie-term',
    title: 'Camaraderie Term',
    latex: 'c(x,t) = \\frac{G}{N_{local}} (1-I) \\left(1 - \\frac{\\rho}{\\rho_{max}}\\right)^m',
    category: 'risk-assessment',
    description: 'Cooperative effects and group resilience',
    variables: [
      { symbol: 'G', meaning: 'Group strength' },
      { symbol: 'I', meaning: 'Independence factor' },
    ],
    explanation:
      'Represents social cohesion that mitigates risk. Coordination decreases as density increases, reflecting the breakdown of order in high-stress crowds.',
  },
];

/* ───────────────────────────────────────────────────────────── */
/* ANALYTICS METRICS - Real-time Simulation Statistics */
/* ───────────────────────────────────────────────────────────── */

export const MOCK_METRICS: MetricData[] = [
  {
    label: 'Current Density',
    value: '3.2',
    unit: 'p/m²',
    trend: 'up',
    trendPercent: 12,
  },
  {
    label: 'Risk Level',
    value: 'Medium',
    unit: 'Index',
    trend: 'stable',
  },
  {
    label: 'Flow Velocity',
    value: '1.8',
    unit: 'm/s',
    trend: 'down',
    trendPercent: -8,
  },
  {
    label: 'Pressure Points',
    value: '7',
    unit: 'zones',
    trend: 'up',
    trendPercent: 2,
  },
  {
    label: 'Exit Flow Rate',
    value: '45',
    unit: 'p/min',
    trend: 'down',
    trendPercent: -15,
  },
  {
    label: 'Safety Score',
    value: '78',
    unit: '%',
    trend: 'down',
    trendPercent: -3,
  },
];

/* ───────────────────────────────────────────────────────────── */
/* ALERTS - Real-time System Notifications */
/* ───────────────────────────────────────────────────────────── */

export const MOCK_ALERTS: AlertItem[] = [
  {
    id: 'alert-1',
    level: 'critical',
    message: 'High pressure zone detected near exit A',
    timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    location: 'Exit A',
  },
  {
    id: 'alert-2',
    level: 'warning',
    message: 'Density approaching critical threshold in corridor B3',
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    location: 'Corridor B3',
  },
  {
    id: 'alert-3',
    level: 'info',
    message: 'Mitigation system activated: Flow optimization engaged',
    timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    location: 'System',
  },
  {
    id: 'alert-4',
    level: 'warning',
    message: 'Velocity gradient spike detected in bottleneck zone',
    timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    location: 'Bottleneck',
  },
];

/* ───────────────────────────────────────────────────────────── */
/* SIMULATION STATE - Current Execution Status */
/* ───────────────────────────────────────────────────────────── */

export const MOCK_SIMULATION_STATE: SimulationState = {
  status: 'running',
  step: 2847,
  elapsed: 113.88,
  progress: 42,
};

/* ───────────────────────────────────────────────────────────── */
/* DASHBOARD CARDS - Feature Highlights */
/* ───────────────────────────────────────────────────────────── */

export const DASHBOARD_FEATURES = [
  {
    id: 'canvas',
    title: 'Live Simulation Canvas',
    description: 'Real-time density and risk heatmaps with interactive cell drawing',
    icon: 'Activity',
    color: 'indigo',
  },
  {
    id: 'formulas',
    title: 'Mathematical Framework',
    description: 'Core equations powering fluid dynamics and risk assessment',
    icon: 'Zap',
    color: 'cyan',
  },
  {
    id: 'analytics',
    title: 'Real-time Analytics',
    description: 'Live metrics tracking density, flow, and safety indices',
    icon: 'BarChart3',
    color: 'emerald',
  },
  {
    id: 'alerts',
    title: 'Hazard Alerts',
    description: 'Multi-level threat detection and mitigation recommendations',
    icon: 'AlertTriangle',
    color: 'emerald',
  },
  {
    id: 'controls',
    title: 'Simulation Controls',
    description: 'Precise parameter adjustment and scenario management',
    icon: 'Settings',
    color: 'indigo',
  },
  {
    id: 'export',
    title: 'Data Export',
    description: 'Generate reports and export simulation data for analysis',
    icon: 'Download',
    color: 'cyan',
  },
];

/* ───────────────────────────────────────────────────────────── */
/* HELPER FUNCTIONS */
/* ───────────────────────────────────────────────────────────── */

export const getAlertColor = (level: AlertItem['level']) => {
  const colors = {
    info: 'text-cyan-cyber',
    warning: 'text-yellow-500',
    critical: 'text-red-500',
  };
  return colors[level];
};

export const getAlertBgColor = (level: AlertItem['level']) => {
  const colors = {
    info: 'bg-cyan-cyber/10 border-cyan-cyber/30',
    warning: 'bg-yellow-500/10 border-yellow-500/30',
    critical: 'bg-red-500/10 border-red-500/30',
  };
  return colors[level];
};

export const getRiskColor = (level: string) => {
  const colors = {
    low: 'text-emerald-math',
    medium: 'text-yellow-500',
    high: 'text-orange-500',
    critical: 'text-red-500',
  };
  return colors[level as keyof typeof colors] || colors.low;
};

export const formatTimestamp = (isoString: string) => {
  const date = new Date(isoString);
  const now = new Date();
  const diffMinutes = Math.floor((now.getTime() - date.getTime()) / 60000);

  if (diffMinutes < 1) return 'just now';
  if (diffMinutes < 60) return `${diffMinutes}m ago`;

  const diffHours = Math.floor(diffMinutes / 60);
  if (diffHours < 24) return `${diffHours}h ago`;

  const diffDays = Math.floor(diffHours / 24);
  return `${diffDays}d ago`;
};
